"""
LIST(ARRAY)
SON  COLLECTIONABLES O UN CONJUNTO DE DATOS/VALORES BAJO UN MISMO NOMBRE,
PARA ACCEDER A LOS VALORES SE HACE CON UN INDICE 
NUMERICO

NOTA: SUS VALORES SI SON MODIFICABLES

LA LISTA ES UNA COLECCION ORDENADA Y MODIFICABLE PERMITE MIEMBROS DUPLICADOS.

"""
import os
os.system("clear")

#FUNCIONES MAS COMUNES EN LAS LISTAS
PAISES=["MEXICO","BRASIL","ESPAÑA","CANADA"]

NUMEROS=[23,12,100,34]

VARIOS=["HOLA",True,33,3.12]

#ORDENAR LAS LISTAS

print(NUMEROS)
print(PAISES)
print(VARIOS)

#ORDENAR
NUMEROS.sort()
print(NUMEROS)
PAISES.sort()
print(PAISES)

#ORDENAR NUMEROS O CADENA DE CARACTERES

#AGREGAR, INSERTAR O AÑADIR UN ELEMENTO A LA LISTA

# 1ER FORMA

print(PAISES)
PAISES.append("HONDURAS")
print(PAISES)


# 2DA FORMA DE INSERTAR EN UNA MANERA ESPECIFICA

#INSERT OCUPA DONDE LO QUIERES INSERTAR Y EL VALOR 

PAISES.insert(1,"HONDURAS")
print(PAISES)

#ELIMINAR, BORRAR O SUPRIMIR UN ELEMENTO A LA LISTA

# 1ER FORMA

PAISES.sort()
print(PAISES)

#POP BORRA POR LA POSICION

PAISES.pop(4)
print(PAISES)

# 2DA FORMA
#SE BORRA POR EL NOMBRE Y NO POR LA POSICION

PAISES.remove("HONDURAS")

#BUSCAR UN ELEMENTO DENTRO DE LA LISTA

"BRASIL" in PAISES

print("BRASIL" in PAISES)

#CONTAR EL NUMERO DE VECES QUE UN ELEMENTO QUE ESTA DENTRO DE UNA LISTA

print(NUMEROS)
NUMEROS.count(12)
print(NUMEROS.count(12))
NUMEROS.insert(1,12)
print(NUMEROS)
print(NUMEROS.count(12))


#DAR LA VUELTA A LOS ELEMENTOS DE UNA LISTA

print(PAISES)
print(NUMEROS)
PAISES.reverse()
NUMEROS.reverse()
print(PAISES)
print(NUMEROS)

#CONOCER EL INDICE O LA POSICION DE UN DATO DE LA LISTA

print(PAISES.index("ESPAÑA"))

#UNIR EL CONTENIDO DE 2 O MAS LISTAS EN UNA SOLA
#NUMEROS=[100,34,23,12,12]
NUMEROS2=[300,500,100]
print(NUMEROS)
print(NUMEROS2)
#EXTEND ES PARA EXTENDER LOS NUMEROS DE LAS LISTAS
NUMEROS.extend(NUMEROS2)
print(NUMEROS)
#TAMBIEN IMPRIME CADENA CON NUMEROS
PAISES.extend(NUMEROS2)
print(PAISES)